In [1]:
!pip install -q mealpy
import mealpy
mealpy.__version__

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 368.2/368.2 kB 7.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.4/20.4 MB 59.4 MB/s eta 0:00:00

'2.5.2'

In [2]:
import random
import pandas as pd
import numpy as np

from sklearn import metrics
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from mealpy.swarm_based.SHO import OriginalSHO

In [3]:
# Datasets
# https://archive.ics.uci.edu/ml/datasets/Zoo

In [4]:
# Names

# 1 -- (41) aardvark, antelope, bear, boar, buffalo, calf, cavy, cheetah, deer, dolphin, elephant, fruitbat, giraffe, girl, goat, gorilla, hamster, hare, leopard, lion, lynx, mink, mole, mongoose, opossum, oryx, platypus, polecat, pony, porpoise, puma, pussycat, raccoon, reindeer, seal, sealion, squirrel, vampire, vole, wallaby,wolf
# 2 -- (20) chicken, crow, dove, duck, flamingo, gull, hawk, kiwi, lark, ostrich, parakeet, penguin, pheasant, rhea, skimmer, skua, sparrow, swan, vulture, wren
# 3 -- (5) pitviper, seasnake, slowworm, tortoise, tuatara
# 4 -- (13) bass, carp, catfish, chub, dogfish, haddock, herring, pike, piranha, seahorse, sole, stingray, tuna
# 5 -- (4) frog, frog, newt, toad
# 6 -- (8) flea, gnat, honeybee, housefly, ladybird, moth, termite, wasp
# 7 -- (10) clam, crab, crayfish, lobster, octopus, scorpion, seawasp, slug, starfish, worm

Zoo_names = ['animal name',
            'hair',
            'feathers',
            'eggs',
            'milk',
            'airborne',
            'aquatic',
            'predator',
            'toothed',
            'backbone',
            'breathes',
            'venomous',
            'fins',
            'legs',
            'tail',
            'domestic',
            'catsize',
            'type']

In [5]:
# Import datasets
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data", 
                   sep = ",",
                   names = Zoo_names)

In [6]:
data.head()

,animal name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [7]:
X = data.iloc[:,0:17]
y = data.iloc[:,17]

In [8]:
X.head()

,animal name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1

In [9]:
y

0      1
1      1
2      4
3      1
4      1
      ..
96     1
97     6
98     1
99     7
100    2
Name: type, Length: 101, dtype: int64

In [10]:
le = LabelEncoder()
X['animal name'] = le.fit_transform(X['animal name'])

In [11]:
X

,animal name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize
0,0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
1,1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1
2,2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0
3,3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1
4,4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,95,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1
97,96,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0
98,97,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1
99,98,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0
100,99,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0

In [12]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1, shuffle=True)

In [13]:
W_ENCODER = LabelEncoder()
W_ENCODER.fit(['uniform', 'distance'])
print(W_ENCODER.inverse_transform([0]))
print(W_ENCODER.inverse_transform([1]))

['distance']
['uniform']

In [14]:
def fitness_function(solution):
    N = int(solution[0])
    w_encoded = int(solution[1])
    w_decoded = W_ENCODER.inverse_transform([w_encoded])[0]

    knn = KNeighborsClassifier(n_neighbors= N, weights = w_decoded)
    knn.fit(X_train, y_train)
    y_predict = knn.predict(X_test)
    return metrics.accuracy_score(y_test, y_predict)

In [15]:
# Problem Defination
problem = {
    "fit_func": fitness_function,
    "lb": [2, 0],
    "ub": [10, 1],
    "minmax": "max",
}

In [16]:
# Termination Function
term_dict = {
    "max_early_stop": 20,
}

In [17]:
# Spotted Hyena Optimization
epoch = 100
pop_size = 50
h_factor = 5.0
N_tried = 10

model = OriginalSHO(epoch, pop_size, h_factor, N_tried)
best_position, best_fitness = model.solve(problem, termination=term_dict)
print(f"Solution: {best_position}, Fitness: {best_fitness}")

INFO:mealpy.swarm_based.SHO.OriginalSHO:Solving single objective optimization problem.
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 1, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.44098 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 2, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.45413 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 3, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.39598 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 4, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.38065 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 5, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.37000 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 6, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.52914 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 7, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.40298 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 8, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.47533 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 9, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.51775 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 10, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.45310 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 11, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.35739 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 12, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.33664 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 13, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.39108 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 14, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.38287 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 15, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.33389 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 16, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.34448 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 17, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.39209 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 18, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.34515 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 19, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.31021 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 20, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.37397 seconds
INFO:mealpy.swarm_based.SHO.OriginalSHO:>Problem: P, Epoch: 21, Current best: 0.41935483870967744, Global best: 0.41935483870967744, Runtime: 0.34993 seconds
WARNING:mealpy.swarm_based.SHO.OriginalSHO:Stopping criterion with early stopping (ES) (fitness-based) occurred. End program!

Solution: [10.  1.], Fitness: 0.41935483870967744

In [ ]:
# Note: In this data all the instances are unique so, without duplicating or recreating the test set, both training and test are just facade.